#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'mysql'
cookbook 'database'
cookbook 'sudo'
cookbook 'nginx'
cookbook 'rbenv', '~> 1.4.0'
cookbook 'logrotate'
cookbook 'bluepill'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

